AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  display-graph

  Sample SAM Template for display-graph

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  DisplayGraphFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: display_graph/
      Handler: app.lambda_handler
      Runtime: python3.8
      Architectures:
        - x86_64
      Events:
        DisplayGraph:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /display-graph
            Method: get
            RequestParameters:
              - method.request.querystring.numbers:
                 Required: true

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  DisplayGraphApi:
    Description: "API Gateway endpoint URL for Prod stage for Display Graph function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/display-graph/"
  DisplayGraphFunction:
    Description: "Display Graph Lambda Function ARN"
    Value: !GetAtt DisplayGraphFunction.Arn
  DisplayGraphFunctionIamRole:
    Description: "Implicit IAM Role created for Display Graph function"
    Value: !GetAtt DisplayGraphFunctionRole.Arn
